### PR TITLE
port to kernel 4.1

### PR DESCRIPTION
**Pull request by ruth0000**
this code is not fully ported and debugged. Only analog input and analog output have been tested. Also it will not work with previous kernels.

### CODE REVIEW

**Comment by shaunmulligan** [comment]
Hey there, I would love to help test this. Is there anything specific I should test first?
Cheers

**Comment by adityapatadia** [comment]
I think you should test whatever is implemented. Here, check if analog inputs and outputs are working. 
It would not be wise to merge this code because not all functions are supported. If someone can work on other functions, it will be great.

Thanks for your efforts.

**Comment by ruth0000** [comment]
Aditya, can comment on what is supported and tested in the orignal bonescript?

Shaun, for the moment only analog input and analog output have been tested. Also, do not use node version 0.12.xx, stick with 0.10.xx

**Comment by ruth0000** [comment]
Digital input and output should be allright now, as well interrupts on digital inputs. The dependencies for serial and i2c are removed. Overlays have been replaced by the overlays that ship with capemanager 4.1.

**Comment by adityapatadia** [comment]
Original bonescript functions are listed in this wiki with examples.
https://github.com/theoctal/octalbonescript/wiki

**Comment by adityapatadia** [comment]
Let me know how to take this forward. Should I create new branch and merge PR there? We will merge to main repo when everything is stable.

**Comment by ruth0000** [comment]
I'm not conversant in all the working of github. But presume that your suggestion is fine. Please let me know if i should take any action.
----Origineel Bericht----
Van : notifications@github.com
Datum : 18/09/2015 07:49
Aan : octalbonescript@noreply.github.com
Cc : paul.van.ruth@wxs.nl
Onderwerp : Re: [octalbonescript] port to kernel 4.1 (#46)
Let me know how to take this forward. Should I create new branch and merge PR there? We will merge to main repo when everything is stable.

**Comment by ruth0000** [comment]
Also note that i've made improvements after the initial pull request. The latest version is stored at github:
https://github.com/ruth0000/octalbonescript_capemgr4_1
 ----Origineel Bericht----
Van : notifications@github.com
Datum : 18/09/2015 07:49
Aan : octalbonescript@noreply.github.com
Cc : paul.van.ruth@wxs.nl
Onderwerp : Re: [octalbonescript] port to kernel 4.1 (#46)
Let me know how to take this forward. Should I create new branch and merge PR there? We will merge to main repo when everything is stable.

**Comment by adityapatadia** [comment]
Hi, just wanted to let you know that I have incorporated some of changes from your PR to master branch. I have published new version 1.1.0-beta so everyone can test it on 4.1 kernel. If everything goes fine, you can expect new stable version with 4.1 kernel support by this Sunday.

**Comment by adityapatadia** [comment]
I need your help to understand the changes you made in DTS files. Let's chat some day when you are free.

**Comment by adityapatadia** [comment]
I request you to submit changes to the DTS files to this repo: https://github.com/cdsteinkuehler/beaglebone-universal-io It's repo which maintains the universal-cape files for linux kernel.

**Pull request closed without merging**
